config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :blogs
  root 'blogs#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :blogs
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

def hello
  
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  
  def index
    @blogs = Blog.all
  end

  def new
    @blog = Blog.new
    respond_to do |format|
     format.js 
    end
  end

  def show    
    @blog = Blog.find(params[:id])
     respond_to do |format|
     format.js 
    end
   end


   
   def create
    @user = User.find(params[:blog][:user_id])
    @blog = @user.blogs.create(blog_params)
     @blogs = Blog.all
    respond_to do |format|
     format.js 
    end
   end

  def edit
    @blog = Blog.find(params[:id])
  end

  def update
    @blog = Blog.find(params[:id])
    @blog.update(blog_params)
    @blogs = Blog.all
     respond_to do |format|
      format.js 
     end
  end


  def destroy
    @blog = Blog.find(params[:id])
    @blog.destroy
     @blogs = Blog.all
    respond_to do |format|
      format.js 
    end  
  end

   private
   def blog_params
    params.require(:blog).permit(:user_id,:title,:description)
   end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
 def index
   @blogs =Blog.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/blogs/_index.html.erb
<div id="b_index">
   <div class="container ">
      <br><br><br><br>
      <% if user_signed_in? %>
      <%= link_to 'New Post', new_blog_path ,:remote => true %>
      <h1>Blogs</h1>
      <table class="table table-striped ">
         <thead >
            <tr>
               <th>Title</th>
               <th>Description</th>
            </tr>
         </thead>
         <tbody>
            <%@blogs.each do |blog| %>
            <tr>
               <td><%= blog.title %></td>
               <td><%= blog.description %></td>
               <td><%= link_to'show',blog_path(blog),:remote =>true%></td>
               <%if blog.user_id == current_user.id%>
               <td><%= link_to'edit',edit_blog_path(blog),:remote => true%></td>
               <td><%= link_to'delete',blog_path(blog),method: :delete,
                  data: {confirm: 'are you sure'},:remote => true %></td>
               <%else%>
               <td>...</td>
               <td>...</td>
               <%end%>
            </tr>
         </tbody>
         <%end%>
      </table>
      <br>
      <% else %>
   </div>
   <% end %>
</div>

app/views/blogs/_pform.html.erb
<div id="blob_form">
<div class="container">
  <%= form_for (@blog),:remote => true  do |form| %>
   
    <div class="field">
     <%= form.hidden_field :user_id, value:current_user.id%>
    </div>
    <div class="field"><br>
      <%= form.label :title %><br>
      <%= form.text_field :title %>
    </div>

    <div class="field"><br>
      <%= form.label :description %><br>
      <%= form.text_area :description %>
    
    
   
    <div class="actions"><br>
      <%= form.submit %>
    </div>
  <% end %>
</div>
</div>

app/views/blogs/_show.html.erb
<div class ="container" id="b_show">
       <h2>Blogs Detail</h2>
         <div>
         <strong>Title:</strong>
          <%=@blog.title%>
        </div>
        <div>
         <strong>Description:</strong>
          <%=@blog.description%>
        </div>
        <br><br>
    </div>  

<%= link_to"blog", blogs_path%>  

app/views/blogs/create.js.erb
$('#blob_form').html("<%= escape_javascript render(:partial => 'blogs/index', :locals => { :blogs => @blogs }) %>");

app/views/blogs/destroy.js.erb
$('#b_index').html("<%= escape_javascript render(:partial => 'blogs/index', :locals => { :blogs => @blogs }) %>");

app/views/blogs/edit.html.erb
<h1>Blogs edit</h1>	
<%=render 'pform'%>
</div>
<%=link_to 'back',root_path%>

app/views/blogs/edit.js.erb
$("#b_index").html("<%= escape_javascript(render 'blogs/pform') %>");

app/views/blogs/index.html.erb
<%=render'blogs/index'%>

app/views/blogs/new.html.erb
<h1>Blogs new</h1>
<%=render 'pform'%>
</div>
<%=link_to 'back',root_path%>

app/views/blogs/new.js.erb
$("#b_index").html("<%= escape_javascript(render 'blogs/pform') %>");

app/views/blogs/show.html.erb
<%=render 'blogs/show'%>

app/views/blogs/show.js.erb
$('#b_index').html("<%= escape_javascript render(:partial => 'blogs/show', :locals => { :blogs => @blogs }) %>");

app/views/blogs/update.js.erb
$('#blob_form').html("<%= j render(:partial => 'blogs/index', :locals => { :blogs => @blogs }) %>");

app/views/layouts/_header.html.erb
<div class="container">
<div class="header" >
 <nav class="navbar navbar-light fixed-top">
   <div class="container">
    <% if user_signed_in? %>
    <div class="float-left w-25 mr-4">
     <p class="text-light ">Logged in as <strong><%= current_user.email  %></strong></p>
   </div>
   <div class="float-right m-4">
     <%= link_to 'Edit user', edit_user_registration_path,  class:'btn btn-outline-dark btn-rounded mt-3 ' %> 
     <%= link_to "Logout", destroy_user_session_path, method: :delete,class:' btn btn-outline-dark btn-rounded mt-3' %>  
  </div>
    <% else %>
     <h1 class='text-primary  '>Welcome to the post</h1>
      <div class="float-right w-25 m_2">
        <%= link_to "Sign up", new_user_registration_path, class:'btn btn-outline-dark btn-rounded  ml-2 '  %> |
        <%= link_to "Login", new_user_session_path, class: 'btn btn-outline-dark btn-rounded ml-2'%>
      </div>
    <% end %>
  </nav>
 </div>  
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DemoApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <p>helo anshul</p>

  <body>
    <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
   <%=render 'layouts/header'%>
    <%= yield %>
  </body>
</html>